apiVersion: 1

datasources:
  - name: ClickHouse Demo
    uid: clickhouse_demo
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: inventory_mart
      username: ${CLICKHOUSE_USERNAME}
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
