apiVersion: 1

datasources:
  - name: ClickHouse Inventory
    uid: clickhouse-inventory
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse_db
      port: 8123
      protocol: http
      defaultDatabase: inventory_mart
      username: password
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: admin
