input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/vendor/jar/jdbc/mssql-jdbc.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "jdbc:sqlserver://${MSSQL_HOST:sqlserver}:${MSSQL_PORT:1433};databaseName=${MSSQL_DATABASE:inventory_demo};encrypt=true;trustServerCertificate=true;loginTimeout=30;"
    jdbc_user => "${MSSQL_USER:sa}"
    jdbc_password => "${MSSQL_SA_PASSWORD:YourStrong!Passw0rd}"

    jdbc_validate_connection => true
    jdbc_validation_timeout => 50

    interval => "${LOGSTASH_POLL_INTERVAL:10s}"
    statement_filepath => "/usr/share/logstash/sql/inventory_incremental.sql"

    use_column_value => true
    tracking_column => "stream_seq"
    tracking_column_type => "numeric"
    record_last_run => true
    clean_run => false
    last_run_metadata_path => "/usr/share/logstash/data/inventory_transactions_last_run.yml"

    jdbc_fetch_size => 5000
    lowercase_column_names => true
  }
}

filter {
  mutate {
    convert => {
      "qty_change" => "integer"
    }
    remove_field => ["stream_seq", "@timestamp", "@version"]
  }
}

output {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS:kafka_broker:9092}"
    topic_id => "${KAFKA_TOPIC:inventory_topic}"
    codec => json
    acks => "1"
    compression_type => "gzip"
  }
}
